#! /bin/sh
# /etc/init.d/inotifyopenhabd

### BEGIN INIT INFO
# Provides:          inotifyopenhabd
# Required-Start:    openhab2
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: inotifyopenhabd server
# Description:       Start / Stop inotifyopenhab server
### END INIT INFO

DAEMON=/usr/local/bin/inotifyopenhab
NAME=inotifyopenhabd
PID=/var/run/inotifyopehab.pid
PPID=`cat $PID`

test -x $DAEMON || exit 0

case "$1" in
    start)
    echo -n "Starting " $NAME ": "
    start-stop-daemon --background --pidfile $PID --make-pidfile --start --exec $DAEMON
    echo $NAME "."
    ;;

    stop)
    echo -n "Shutting " $NAME ": "
    start-stop-daemon --stop --oknodo --retry 30 --ppid $PPID
    echo $NAME "."
    ;;

    restart)
    echo -n "Restarting " $NAME ": "
    start-stop-daemon --stop --oknodo --retry 30 --ppid $PPID
    start-stop-daemon --background --pidfile $PID --make-pidfile --start --exec $DAEMON
    echo $NAME "."
    ;;

    *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
exit 0
