#! /bin/sh
# /etc/init.d/inotifyopenhabd

### BEGIN INIT INFO
# Provides:          inotifyopenhabd
# Required-Start:    openhab2
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: inotifyopenhabd server
# Description:       Start / Stop inotifyopenhab server
### END INIT INFO

DAEMON=nohup /usr/local/bin/inotifyopenhab < /dev/null &
NAME=inotifyopenhabd

test -x $DAEMON || exit 0

case "$1" in
    start)
    echo -n "Starting inotifyopenhabd: "
    start-stop-daemon --start --exec $DAEMON
    echo "inotifyopenhabd."
    ;;
    stop)
    echo -n "Shutting down inotifyopenhabd:"
    start-stop-daemon --stop --oknodo --retry 30 --exec $DAEMON
    echo "inotifyopenhabd."
    ;;

    restart)
    echo -n "Restarting inotifyopenhabd: "
    start-stop-daemon --stop --oknodo --retry 30 --exec $DAEMON
    start-stop-daemon --start --exec $DAEMON
    echo "inotifyopehabd."
    ;;

    *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
exit 0
