#! /bin/sh
# /etc/init.d/noip2

### BEGIN INIT INFO
# Provides:          noip2
# Required-Start:    networking
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: noip2 server
# Description:       Start / Stop noip2 server
### END INIT INFO

DAEMON=/usr/local/bin/noip2
NAME=noip2
PID=/var/run/noip2.pid

test -x $DAEMON || exit 0

case "$1" in
    start)
    echo -n "Starting " $NAME ": "
    start-stop-daemon --background --pidfile $PID --make-pidfile --start --exec $DAEMON
    echo $NAME "."
    ;;

    stop)
    echo -n "Shutting " $NAME ": "
    start-stop-daemon --stop --oknodo --retry 30 --remove-pidfile --pidfile $PID
    echo $NAME "."
    ;;

    restart)
    echo -n "Restarting " $NAME ": "
    start-stop-daemon --stop --oknodo --retry 30 --remove-pidfile --pidfile $PID
    start-stop-daemon --background --pidfile $PID --make-pidfile --start --exec $DAEMON
    echo $NAME "."
    ;;

    *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
exit 0
