#! /bin/sh
# /etc/init.d/openhabot

### BEGIN INIT INFO
# Provides:          openhabot
# Required-Start:    networking
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: serveo server
# Description:       Start / Stop serveo server
### END INIT INFO

DAEMON=nohup /usr/local/bin/openhabot < /dev/null &
NAME=serveo

test -x $DAEMON || exit 0

case "$1" in
    start)
    echo -n "Starting OpenHaBot: "  $DAEMON
    start-stop-daemon --start --exec $DAEMON
    echo "serveo."
    ;;
    stop)
    echo -n "Shutting OpenHaBot:"
    start-stop-daemon --stop --oknodo --retry 30 --exec $DAEMON
    echo "serveo."
    ;;

    restart)
    echo -n "Restarting OpenHaBot: "
    start-stop-daemon --stop --oknodo --retry 30 --exec $DAEMON
    start-stop-daemon --start --exec $DAEMON
    echo "serveo."
    ;;

    *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
exit 0
