#! /bin/sh
# /etc/init.d/serveo

### BEGIN INIT INFO
# Provides:          serveo
# Required-Start:    networking
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: serveo server
# Description:       Start / Stop serveo server
### END INIT INFO

DAEMON=/usr/lib/autossh/autossh
NAME=serveo
DAEMON_OPTS="-M 0 -i /root/.ssh/id_rsa -R webhook-oh2.craftandtechnology.com:80:localhost:1337 serveo.net"
PID=/var/run/serveo.pid

test -x $DAEMON || exit 0

case "$1" in
    start)
    echo -n "Starting " $NAME ": "
    start-stop-daemon --background --pidfile $PID --make-pidfile --start --exec $DAEMON -- $DAEMON_OPTS
    echo $NAME "."
    ;;

    stop)
    echo -n "Shutting " $NAME ": "
    start-stop-daemon --stop --oknodo --retry 30 --remove-pidfile --pidfile $PID
    echo $NAME "."
    ;;

    restart)
    echo -n "Restarting " $NAME ": "
    start-stop-daemon --stop --oknodo --retry 30 --remove-pidfile --pidfile $PID
    start-stop-daemon --background --pidfile $PID --make-pidfile --start --exec $DAEMON -- $DAEMON_OPTS
    echo $NAME "."
    ;;

    *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
exit 0
